# Generated by Django 5.1.2 on 2024-10-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_cursos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=80)),
                ('ap_paterno', models.CharField(max_length=80)),
                ('ap_materno', models.CharField(max_length=80)),
                ('escolaridad', models.CharField(max_length=80)),
                ('correo', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=15)),
                ('likedin', models.CharField(max_length=255)),
                ('experiencia', models.TextField(blank=True)),
                ('curriculum', models.FileField(upload_to='filesPDF/CV/')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
