# Generated by Django 5.1.2 on 2024-10-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_solicitudempleo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudempleo',
            name='curriculum',
            field=models.FileField(upload_to='static/filesPDF/CV/'),
        ),
    ]
