# Generated by Django 5.1.2 on 2024-10-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_alter_solicitudempleo_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudempleo',
            name='curriculum',
            field=models.FileField(upload_to='filesPDF/CV/'),
        ),
    ]
