# Generated by Django 5.1.2 on 2024-10-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_departamentos_puestos_usuariosga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosga',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
