# Generated by Django 5.1.2 on 2024-10-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_alter_usuariosga_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='empresa',
            field=models.CharField(max_length=50),
        ),
    ]
