# Generated by Django 5.1.2 on 2024-10-19 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_alter_empresas_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DominiosRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaEquiposMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaEquiposMouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaEquiposTeclado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MemoriasRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistemaOperativo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDiscoC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disco', models.CharField(max_length=50)),
                ('capacidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDiscoD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disco', models.CharField(max_length=50)),
                ('capacidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VersionesOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=50)),
                ('sufijo_DNS', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('num_Serie_Equipo', models.CharField(max_length=50)),
                ('modelo_monitor', models.CharField(max_length=50)),
                ('monitor_serie', models.CharField(max_length=50)),
                ('procesador', models.CharField(max_length=100)),
                ('particion', models.BooleanField(default=False)),
                ('adaptador_USB_RJ45', models.BooleanField(default=False)),
                ('mac_Ethernet', models.CharField(max_length=100)),
                ('mac_WIFI', models.CharField(max_length=100)),
                ('ip_activa', models.CharField(max_length=50)),
                ('nombre_usuario_pc', models.CharField(max_length=50)),
                ('antivirus', models.BooleanField(default=False)),
                ('pdf', models.BooleanField(default=False)),
                ('sygnology', models.BooleanField(default=False)),
                ('anydesk', models.BooleanField(default=False)),
                ('one_drive', models.BooleanField(default=False)),
                ('mba3', models.BooleanField(default=False)),
                ('netsuite', models.BooleanField(default=False)),
                ('bizagi', models.BooleanField(default=False)),
                ('tsplus', models.BooleanField(default=False)),
                ('impresora_b_n', models.BooleanField(default=False)),
                ('impresora_color', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.departamentos')),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.dominiosred')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.puestos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.usuariosga')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.marcaequipos')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.marcaequiposmonitor')),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.marcaequiposmouse')),
                ('teclado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.marcaequiposteclado')),
                ('memoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.memoriasram')),
                ('sistema_operativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.sistemaoperativo')),
                ('tipo_disco_C', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.tipodiscoc')),
                ('yipo_disco_D', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.tipodiscod')),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.tipoequipos')),
                ('version_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.versionesoffice')),
            ],
        ),
    ]
