# Generated by Django 5.1.2 on 2024-10-21 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_dominiosred_marcaequipos_marcaequiposmonitor_and_more'),
        ('Dashboard', '0009_tiponoticia_noticias'),
    ]

    operations = [
    ]
