# Generated by Django 5.1.2 on 2024-10-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_dominiosred_marcaequipos_marcaequiposmonitor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventariosoporte',
            old_name='yipo_disco_D',
            new_name='tipo_disco_D',
        ),
    ]
