# Generated by Django 5.1.2 on 2024-10-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_tiponoticia_noticias'),
        ('Dashboard', '0010_rename_yipo_disco_d_inventariosoporte_tipo_disco_d'),
    ]

    operations = [
    ]
