# Generated by Django 5.1.2 on 2024-10-22 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_merge_20241021_1746'),
        ('Dashboard', '0012_inventariosoporte_responsiva'),
    ]

    operations = [
    ]
