# Generated by Django 5.1.2 on 2024-10-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_alter_cursos_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicaciones',
            name='latitud',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ubicaciones',
            name='longitud',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
