# Generated by Django 5.1.2 on 2024-10-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0018_alter_inventariosoporte_responsiva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosoporte',
            name='responsiva',
            field=models.FileField(upload_to='static/Media/filesPDF/Responsivas_Soporte/'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='imagen',
            field=models.ImageField(upload_to='static/Media/FotosNoticia/'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='documento',
            field=models.FileField(upload_to='static/filesPDF/ISO/'),
        ),
    ]
