# Generated by Django 5.1.2 on 2024-10-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0020_alter_inventariosoporte_responsiva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagen',
            field=models.ImageField(upload_to='Media/FotosNoticia/'),
        ),
    ]
