# Generated by Django 5.1.2 on 2024-10-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0021_alter_noticias_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagen',
            field=models.ImageField(upload_to='./static/Media/FotosNoticia/'),
        ),
    ]
