# Generated by Django 5.1.2 on 2024-10-31 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0023_alter_noticias_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosoporte',
            name='responsiva',
            field=models.FileField(upload_to='filesPDF/Responsivas_Soporte/'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='imagen',
            field=models.ImageField(upload_to='FotosNoticia/'),
        ),
        migrations.AlterField(
            model_name='usuariosga',
            name='foto',
            field=models.ImageField(upload_to='FotosPlantilla/'),
        ),
    ]
