# Generated by Django 5.1.2 on 2024-11-06 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0024_alter_inventariosoporte_responsiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantes',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.empresas'),
        ),
    ]
